import { SQLExporter } from '../../src/core/exporter/sql-exporter';
import { TableData, SchemaDefinition, GenerationOptions } from '../../src/types';

describe('SQLExporter', () => {
  let exporter: SQLExporter;
  let schema: SchemaDefinition;
  let options: GenerationOptions;

  beforeEach(() => {
    exporter = new SQLExporter();
    schema = {
      tables: [
        {
          name: 'users',
          columns: [
            { name: 'id', type: 'INTEGER', nullable: false },
            { name: 'name', type: 'VARCHAR', nullable: false }
          ],
          constraints: []
        }
      ]
    };
    options = {
      count: 100,
      format: 'sql'
    };
  });

  describe('export', () => {
    it('should generate SQL INSERT statements', () => {
      const tableData: TableData[] = [
        {
          table: 'users',
          records: [
            { id: 1, name: 'John' },
            { id: 2, name: 'Jane' }
          ]
        }
      ];

      const sql = exporter.export(tableData, schema, options);

      expect(sql).toContain('INSERT INTO');
      expect(sql).toContain('users');
      expect(sql).toContain('John');
      expect(sql).toContain('Jane');
    });

    it('should include header comments', () => {
      const tableData: TableData[] = [
        {
          table: 'users',
          records: [{ id: 1, name: 'John' }]
        }
      ];

      const sql = exporter.export(tableData, schema, options);

      expect(sql).toContain('Generated by @claude-code/testdatagen');
      expect(sql).toContain('Timestamp:');
      expect(sql).toContain('Record count:');
    });

    it('should handle empty records', () => {
      const tableData: TableData[] = [
        {
          table: 'users',
          records: []
        }
      ];

      const sql = exporter.export(tableData, schema, options);

      expect(sql).toContain('No records generated');
    });

    it('should escape special characters in strings', () => {
      const tableData: TableData[] = [
        {
          table: 'users',
          records: [
            { id: 1, name: "O'Brien" }
          ]
        }
      ];

      const sql = exporter.export(tableData, schema, options);

      expect(sql).toContain("O''Brien");
    });

    it('should handle NULL values', () => {
      const tableData: TableData[] = [
        {
          table: 'users',
          records: [
            { id: 1, name: null }
          ]
        }
      ];

      const sql = exporter.export(tableData, schema, options);

      expect(sql).toContain('NULL');
    });

    it('should handle boolean values', () => {
      const tableData: TableData[] = [
        {
          table: 'users',
          records: [
            { id: 1, is_active: true, is_deleted: false }
          ]
        }
      ];

      const sql = exporter.export(tableData, schema, options);

      expect(sql).toContain('TRUE');
      expect(sql).toContain('FALSE');
    });

    it('should batch INSERT statements', () => {
      const records = [];
      for (let i = 1; i <= 250; i++) {
        records.push({ id: i, name: `User ${i}` });
      }

      const tableData: TableData[] = [
        {
          table: 'users',
          records
        }
      ];

      const sql = exporter.export(tableData, schema, options);

      const insertCount = (sql.match(/INSERT INTO/g) || []).length;
      expect(insertCount).toBeGreaterThan(1);
    });

    it('should escape column identifiers', () => {
      const tableData: TableData[] = [
        {
          table: 'users',
          records: [
            { id: 1, 'user-name': 'John' }
          ]
        }
      ];

      const sql = exporter.export(tableData, schema, options);

      expect(sql).toContain('"user-name"');
    });

    it('should handle numbers correctly', () => {
      const tableData: TableData[] = [
        {
          table: 'products',
          records: [
            { id: 1, price: 99.99, quantity: 42 }
          ]
        }
      ];

      const sql = exporter.export(tableData, schema, options);

      expect(sql).toContain('99.99');
      expect(sql).toContain('42');
    });

    it('should handle JSON values', () => {
      const tableData: TableData[] = [
        {
          table: 'users',
          records: [
            { id: 1, metadata: { key: 'value' } }
          ]
        }
      ];

      const sql = exporter.export(tableData, schema, options);

      expect(sql).toContain('{"key":"value"}');
    });
  });

  describe('exportSeparateFiles', () => {
    it('should create separate file for each table', () => {
      const tableData: TableData[] = [
        {
          table: 'users',
          records: [{ id: 1, name: 'John' }]
        },
        {
          table: 'products',
          records: [{ id: 1, name: 'Product A' }]
        }
      ];

      const files = exporter.exportSeparateFiles(tableData, schema, options);

      expect(files.size).toBe(2);
      expect(files.has('users.sql')).toBe(true);
      expect(files.has('products.sql')).toBe(true);
    });

    it('should include table-specific headers', () => {
      const tableData: TableData[] = [
        {
          table: 'users',
          records: [{ id: 1, name: 'John' }]
        }
      ];

      const files = exporter.exportSeparateFiles(tableData, schema, options);
      const usersSql = files.get('users.sql');

      expect(usersSql).toContain('Table: users');
      expect(usersSql).toContain('Records: 1');
    });
  });

  describe('exportWithDelete', () => {
    it('should include DELETE statements', () => {
      const tableData: TableData[] = [
        {
          table: 'users',
          records: [{ id: 1, name: 'John' }]
        }
      ];

      const sql = exporter.exportWithDelete(tableData, schema, options);

      expect(sql).toContain('DELETE FROM');
      expect(sql).toContain('SET FOREIGN_KEY_CHECKS = 0');
      expect(sql).toContain('SET FOREIGN_KEY_CHECKS = 1');
    });

    it('should delete in reverse order', () => {
      const tableData: TableData[] = [
        {
          table: 'users',
          records: [{ id: 1, name: 'John' }]
        },
        {
          table: 'orders',
          records: [{ id: 1, user_id: 1 }]
        }
      ];

      const sql = exporter.exportWithDelete(tableData, schema, options);

      const deleteUsersIndex = sql.indexOf('DELETE FROM "users"');
      const deleteOrdersIndex = sql.indexOf('DELETE FROM "orders"');
      const insertUsersIndex = sql.indexOf('INSERT INTO "users"');

      expect(deleteOrdersIndex).toBeLessThan(deleteUsersIndex);
      expect(deleteUsersIndex).toBeLessThan(insertUsersIndex);
    });
  });

  describe('exportWithTransaction', () => {
    it('should wrap in BEGIN/COMMIT', () => {
      const tableData: TableData[] = [
        {
          table: 'users',
          records: [{ id: 1, name: 'John' }]
        }
      ];

      const sql = exporter.exportWithTransaction(tableData, schema, options);

      expect(sql).toContain('BEGIN;');
      expect(sql).toContain('COMMIT;');

      const beginIndex = sql.indexOf('BEGIN;');
      const commitIndex = sql.indexOf('COMMIT;');
      const insertIndex = sql.indexOf('INSERT INTO');

      expect(beginIndex).toBeLessThan(insertIndex);
      expect(insertIndex).toBeLessThan(commitIndex);
    });
  });
});
